replicaCount: 3

image:
  repository: elliotl9213/audio-to-text
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  hosts:
    - host: audio-to-text-user-elliot.lab.sspcloud.fr
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: audio-to-text-tls
      hosts:
        - audio-to-text-user-elliot.lab.sspcloud.fr

resources:
  limits:
    memory: 4Gi
    nvidia.com/gpu: 1
  requests:
    memory: 2Gi
    nvidia.com/gpu: 1
