replicaCount: 1

image:
  repository: elliotl9213/audio-to-text
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  hosts:
    - host: audio-to-text-user-elliot.lab.sspcloud.fr
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    memory: 16Gi
    nvidia.com/gpu: 1
  requests:
    memory: 16Gi
    nvidia.com/gpu: 1
